### ISSUE TITLE
Cannot load shared libray

### ISSUE THREAD

**Issue by gabrielgbs97** [romen/libsuola#12]
`$ openssl engine -c libsoula`
`139942924456384:error:25066067:DSO support routines:dlfcn_load:could not load the shared library:../crypto/dso/dso_dlfcn.c:117:filename(/usr/lib/x86_64-linux-gnu/engines-1.1/libsoula.so): /usr/lib/x86_64-linux-gnu/engines-1.1/libsoula.so: cannot open shared object file: No such file or directory
139942924456384:error:25070067:DSO support routines:DSO_load:could not load the shared library:../crypto/dso/dso_lib.c:162:
139942924456384:error:260B6084:engine routines:dynamic_load:dso not found:../crypto/engine/eng_dyn.c:414:
139942924456384:error:2606A074:engine routines:ENGINE_by_id:no such engine:../crypto/engine/eng_list.c:335:id=libsoula`

If i check the file in file explorer I assure that it is created and it exists, also tried to execute with sudo with the same result. I have done al the steps specified by documentation, but I am using OpenSSL 1.1.1 that came with ubuntu

**Comment by bbbrumley** [comment]
Howdy,

Thanks for the report.

What version of Ubuntu are you on?

What does `ldd /usr/lib/x86_64-linux-gnu/engines-1.1/libsoula.so` give you?

What does `openssl version -a` give you?

**Comment by bbbrumley** [comment]
Or is it just a typo :see_no_evil: 

    $ openssl engine -c libsoula

    $ openssl engine -c libsuola

**Comment by romen** [comment]
@gabrielgbs97 do you have any update on this? Indeed it seems like it might have been a typo on the argument?

**Comment by gabrielgbs97** [comment]
Sorry for not getting back, it was a typo!

**Comment by romen** [comment]
Thanks @gabrielgbs97 for the feedback!

Closing this!
